Fix for exporting messages with deleted videos
enscogitans/vk-tg-chat-transferring pull request #3
Opened 2023-12-07 20:03 UTC by AntonSamokat

При попытке выгрузить сообщения, в которых содержатся ссылки на удалённые видео, появляется ошибка:

```
    return Video.parse(attachment_dict)
  File "vk-tg-chat-transferring/vk_exporter/types.py", line 168, in parse
    image_url=Video._pick_best_image(video_dict["image"])["url"],
KeyError: 'image'
```

Такие видео не содержат параметр image:

```
{
  'response_type': 'full',
  'access_key': '60257049b67d07add7',
  'can_like': 0,
  'can_repost': 0,
  'can_add_to_faves': 0,
  'can_add': 0,
  'is_from_message': 1,
  'date': 1553745079,
  'description': 'Привет! Меня зовут Кристина. Я - экстраверт и с удовольствием делю свою жизнь с другими людьми. Мой блог является личным (т.е.не корпоративным, не тематическим и тем более – не официальное СМИ) и потому правила в нем устанавливает автор)\nПОДПИСЫВАЙСЯ НА МОЙ КАНАЛ, ВМЕСТЕ ВЕСЕЛЕЕ! \nhttps://www.youtube.com/channel/UC1fJOMby-6jckOM5cHk8o\n\nПОХОЖИЕ ВИДЕО:\n\nКАНАЛ МОЕЙ ДОЧЕРИ КАССАНДРЫ  ТУТ: https://www.youtube.com/channel/UCGerPm93JK0l3jtuckCgaag\n\nКАК И ГДЕ Я ПОЗНАКОМИЛАСЬ С МУЖЕМ-АМЕРИКАНЦЕМ ТУТ:https://www.yout',
  'id': 456239021,
  'owner_id': 511407140,
  'title': '223.ВЫ СПРАШИВАЛИ, КАК СТИВ ОТНОСИТСЯ К ВЕГЕТАРИАНСТВУ',
  'is_favorite': False,
  'restriction': {
    'title': 'Видео удалено',
    'text': 'Видео недоступно на стороннем сайте',
    'blur': 0,
    'can_play': 0,
    'can_preview': 1,
    'card_icon': [
      {
        'url': 'https://sun1-84.userapi.com/PKwlfI-__N9DoDRYNyLWpwpPP-Ad4TOpPAhoQQ/Lc4Vd6GSZ0A.png',
        'width': 28,
        'height': 28
      },
      {
        'url': 'https://sun1-92.userapi.com/5Wfvthkn_ycSr4E_eXBMYAXjSrVE2nnfVoJibg/wYwHBiPd81w.png',
        'width': 56,
        'height': 56
      },
      {
        'url': 'https://sun1-20.userapi.com/vu5j796NBN9KEdWMOLHHQmn4caDOBeVqtZbeCg/o2AvDMUsDSE.png',
        'width': 84,
        'height': 84
      },
      {
        'url': 'https://sun1-20.userapi.com/VzERX7xntwpwEmEPMg61Syd5dvu_DExUFolopg/4MHM8Fj0l0A.png',
        'width': 112,
        'height': 112
      }
    ],
    'disclaimer_type': 0,
    'list_icon': [
      {
        'url': 'https://sun1-25.userapi.com/cixAU0wWptztuQX8fK5FbXRL-NJGrxsL3Bfz_Q/uvOL4jFt1ho.png',
        'width': 56,
        'height': 56
      },
      {
        'url': 'https://sun1-89.userapi.com/O5lhgSfQJYxMzJSFERcU4_G3qRirlBS9V9cLCQ/gzdpowSK38A.png',
        'width': 112,
        'height': 112
      },
      {
        'url': 'https://sun1-86.userapi.com/QZGtIXudh2_gp44xjAyvJQj1NTPSRsKz84-fHQ/7qwIw34hzxU.png',
        'width': 168,
        'height': 168
      },
      {
        'url': 'https://sun1-87.userapi.com/sUmKjS6wSYkujitZ3VbW0jxhgD98TKqhWU3Nqg/bx36C9KxPts.png',
        'width': 224,
        'height': 224
      }
    ],
    'icon_name': 'delete_outline'
  },
  'added': 0,
  'track_code': 'video_8422b6c4B_rj6eVucz4U7zWkJCN9iTMkkDaMreL6RbRyysPD6YIE6dbY1FpDCSXbBfsQFku7AB2gBA',
  'type': 'video',
  'views': 1,
  'platform': 'YouTube',
  'can_dislike': 1
}
```

Для сравнения данные для существующего видео, которое не вызывает проблемы (параметр image существует):

```
{
  'files': {
    'external': 'https://www.youtube.com/watch?v=8dVtBAWbZ14'
  },
  'response_type': 'full',
  'access_key': 'c6db2c935910d4f1f4',
  'can_like': 0,
  'can_repost': 0,
  'can_add_to_faves': 0,
  'can_add': 0,
  'can_play_in_background': 1,
  'can_download': 0,
  'is_from_message': 1,
  'date': 1553666759,
  'description': 'Видео с концерта в Киеве группы "РОЖДЕСТВО" в 2011 году в Доме офицеров\n\n\n\n\n\n\n#ГруппаРождество',
  'duration': 324,
  'image': [
    {
      'url': 'https://sun1-84.userapi.com/c846520/v846520294/1d51bf/eqnkqbfQzcQ.jpg',
      'width': 130,
      'height': 96,
      'with_padding': 1
    },
    {
      'url': 'https://sun1-95.userapi.com/c846520/v846520294/1d51c0/drQw8KxJG_c.jpg',
      'width': 160,
      'height': 120,
      'with_padding': 1
    },
    {
      'url': 'https://sun1-16.userapi.com/c846520/v846520294/1d51c1/RbIo3OvLGdc.jpg',
      'width': 320,
      'height': 240,
      'with_padding': 1
    },
    {
      'url': 'https://sun1-47.userapi.com/c846520/v846520294/1d51c2/pRM-3Cuk4Og.jpg',
      'width': 800,
      'height': 450,
      'with_padding': 1
    }
  ],
  'id': 456239018,
  'owner_id': 511407140,
  'title': 'группа "Рождество" - песня "Так хочется жить!"',
  'is_favorite': False,
  'player': 'https://www.youtube.com/embed/8dVtBAWbZ14?__ref=vk.web2',
  'added': 0,
  'track_code': 'video_42b30869O_0BQBmxZejC9qTyi6XCRPVnfIKlbnM5p5qW6ePZJ2447jRxKIVV3_PClK2_kPR2xl5Msw',
  'type': 'video',
  'views': 1,
  'platform': 'YouTube',
  'can_dislike': 1
}
```

Возможный вариант фикса - это устанавливать ссылку на картинку для удалённых видео в качестве пустой строки:

```
vk-tg-chat-transferring/vk_exporter/types.py

    @staticmethod
    def parse(video_dict: dict) -> "Video":
        image_url: str
        try:
            video_images = video_dict["image"]
            best_image = Video._pick_best_image(video_images)
            image_url = best_image["url"]
        except KeyError as e:  # there is no 'image' param for removed videos
            image_url = ""

        return Video(
            title=video_dict["title"],
            id=video_dict["id"],
            owner_id=video_dict["owner_id"],
            width=video_dict.get("width", 0),
            height=video_dict.get("height", 0),
            duration=video_dict.get("duration", 0),  # if the content is restricted, 'duration' field is missing
            content_restricted="restriction" in video_dict,
            image_url=image_url,
            access_key=video_dict.get("access_key"),
        ) 
```

2023-12-07 20:46 UTC, enscogitans requested changes

2023-12-07 20:46 UTC, enscogitans commented on vk_exporter/types.py
> +
* Эту часть следует выделить в отдельный static метод типа `def _try_get_image_url(video_dict)`
* Не стоит использовать исключения. Лучше переписать, явно проверяя, лежит ли ключ в словаре: `if "image" not in video_dict: return None`
* Вместо пустой строки следует возвращать `None`
* Для этого в строке 155 нужно дополнительно изменить тип переменной на `image_url: Optional[str]`
* В файле `media_converter.py` в строке 116 используется переменная `image_url`. Это место тоже нужно будет поправить, предполагая, что переменная теперь может быть равна `None`

2024-02-14 21:01 UTC, AntonSamokat commented on vk_exporter/types.py
> +
Внёс исправления. К сожалению полноценно протестировать написанный код уже не имею возможности.

2024-02-19 20:58 UTC, AntonSamokat commented
Перенёс pull request [сюда](https://github.com/enscogitans/vk-tg-chat-transferring/pull/6)
Текущий pull request закрываю, т.к. он по ошибке был сделан в master бранче.

2024-02-19 20:58 UTC, closed without merging